spring:
  datasource:
    url: jdbc:mysql://trip-prod.cn8ukqmcgxhp.ap-northeast-2.rds.amazonaws.com:3306/trip_dev
    username: admin
    password: pthkjkb2134!
    driver-class-name: com.mysql.cj.jdbc.Driver
