spring:
  datasource:
    url: jdbc:mysql://trip-prod.cn8ukqmcgxhp.ap-northeast-2.rds.amazonaws.com:3306/trip_dev
    username: admin
    password: pthkjkb2134!
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: e30f14199b373b2d72ea00fea4f1cd4e

#TODO github action secret에 추가 (encode해서)
jwt:
  token-secret: OWIzMzZmMTA3MWU2NTFhNjQwZjM4ZWZlMzFkOGJlMzJmOGI0YTUyZmRmZWNmNGY1NWI5OGMyY2FkYjVhNGY4NDJhOTZlZDM2MTg3YTQ1NzE4NDcwYWExM2Q3NmVhMWI2YzFhMmVhNzUzZGFmOWVkZjQzMmIyOWQ4YWEwMTQyMWQ=
  access-token-time: 600000
  refresh-token-time: 31557600000
