spring:
  datasource:
    url: jdbc:mysql://trip-prod.cn8ukqmcgxhp.ap-northeast-2.rds.amazonaws.com:3306/trip_dev
    username: admin
    password: pthkjkb2134!
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: d49b684fd87dd0dfd78a1963265a85bd
            client-secret: hUZ82MTWYF2AOnvBapg5VPIfGAxjZroc

jwt:
  token-secret: OWIzMzZmMTA3MWU2NTFhNjQwZjM4ZWZlMzFkOGJlMzJmOGI0YTUyZmRmZWNmNGY1NWI5OGMyY2FkYjVhNGY4NDJhOTZlZDM2MTg3YTQ1NzE4NDcwYWExM2Q3NmVhMWI2YzFhMmVhNzUzZGFmOWVkZjQzMmIyOWQ4YWEwMTQyMWQ=
  access-token-time: 600000
  refresh-token-time: 31557600000
